In [1]:
import numpy as np

In [2]:
from time import process_time

In [3]:
list = [i for i in range(10000)]
start_time = process_time()
list = [i*2 for i in list]
end_time = process_time()
print(end_time - start_time)

0.0016119080000001063


In [4]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array = np_array * 2
end_time = process_time()
print(end_time - start_time)

0.0013168119999997785


Numpy Array


In [5]:
list = [1,2,3,4]
print(list)
type(list)

[1, 2, 3, 4]


list

In [6]:
numpy_array = np.array([1,2,3,4])
print(numpy_array)
type(numpy_array)

[1 2 3 4]


numpy.ndarray

In [7]:
#One dimensional array
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [8]:
a.shape

(4,)

In [9]:
#Two dimensional array
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [10]:
b.shape

(2, 3)

In [11]:
c = np.array([[1,2,3],[4,5,6]], dtype=float)
print(c)

[[1. 2. 3.]
 [4. 5. 6.]]


Initial Placeholders in numpy array


In [12]:
x = np.zeros((2,3))
print(x)

[[0. 0. 0.]
 [0. 0. 0.]]


In [13]:
y = np.ones((2,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]]


In [15]:
z = np.full((3,4),6)
print(z)

[[6 6 6 6]
 [6 6 6 6]
 [6 6 6 6]]


In [16]:
#Identity matrix
i = np.eye(5)
print(i)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [17]:
#Random values
r = np.random.random((3,4))
print(r)

[[0.68078179 0.83716422 0.71721658 0.4484208 ]
 [0.34637335 0.60196101 0.56417837 0.69258627]
 [0.66353254 0.83428981 0.33345087 0.78410122]]


In [19]:
#Random integer values between a range
r1 = np.random.randint(1,10,(4,5))
print(r1)

[[9 4 6 4 4]
 [9 3 3 8 5]
 [5 4 8 3 6]
 [3 2 5 5 9]]


In [20]:
#Array of evenly spaced value
e = np.linspace(10,30,5)
print(e)

[10. 15. 20. 25. 30.]


In [21]:
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [22]:
#List to numpy_array

list = [1,2,3,4,5]
np_array = np.asarray(list)
print(np_array)

[1 2 3 4 5]


Analyzing numpy array


In [23]:
c = np.random.randint(1,10,(3,4))
print(c)

[[6 3 8 4]
 [5 1 1 7]
 [9 5 1 2]]


In [24]:
c.shape

(3, 4)

In [25]:
#Number of dimension
c.ndim

2

In [26]:
c.size

12

In [27]:
c.dtype

dtype('int64')

Mathematical operations on a np array

In [28]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]

print(list1 + list2) #concatenate or join list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [30]:
a = np.random.randint(0,10,(3,4))
b= np.random.randint(10,20,(3,4))
print(a)
print(b)

[[0 4 9 5]
 [6 4 2 3]
 [1 7 4 3]]
[[10 11 10 19]
 [13 15 16 15]
 [10 17 18 14]]


In [31]:
print(a+b)

[[10 15 19 24]
 [19 19 18 18]
 [11 24 22 17]]


In [32]:
print(a-b)

[[-10  -7  -1 -14]
 [ -7 -11 -14 -12]
 [ -9 -10 -14 -11]]


In [33]:
print(a*b)

[[  0  44  90  95]
 [ 78  60  32  45]
 [ 10 119  72  42]]


In [34]:
print(a/b)

[[0.         0.36363636 0.9        0.26315789]
 [0.46153846 0.26666667 0.125      0.2       ]
 [0.1        0.41176471 0.22222222 0.21428571]]


In [35]:
a = np.random.randint(0,10,(3,4))
b= np.random.randint(10,20,(3,4))

In [36]:
print(np.add(a,b))

[[14 16 16 13]
 [10 18 18 18]
 [19 23 23 27]]


In [37]:
print(np.subtract(a,b))

[[ -6 -12 -10  -7]
 [-10  -8  -4  -6]
 [ -3  -5  -5 -11]]


In [38]:
print(np.multiply(a,b))

[[ 40  28  39  30]
 [  0  65  77  72]
 [ 88 126 126 152]]


In [39]:
print(np.divide(a,b))

[[0.4        0.14285714 0.23076923 0.3       ]
 [0.         0.38461538 0.63636364 0.5       ]
 [0.72727273 0.64285714 0.64285714 0.42105263]]


Array Manipulation


In [40]:
array = np.random.randint(0,10,(3,4))
print(array)
print(array.shape)

[[8 2 2 6]
 [9 8 7 0]
 [3 1 5 8]]
(3, 4)


In [41]:
#Transpose
trans = np.transpose(array)
print(trans)

[[8 9 3]
 [2 8 1]
 [2 7 5]
 [6 0 8]]


In [42]:
print(trans.shape)

(4, 3)


In [43]:
trans2 = array.T
print(trans2)

[[8 9 3]
 [2 8 1]
 [2 7 5]
 [6 0 8]]


In [44]:
print(trans2.shape)

(4, 3)


In [45]:
#reshaping array
array = np.random.randint(0,10,(3,4))
print(array)

[[5 6 5 2]
 [2 7 3 4]
 [4 1 6 4]]


In [48]:
reshape = array.reshape(4,3)
print(reshape)

[[5 6 5]
 [2 2 7]
 [3 4 4]
 [1 6 4]]
